[
  {"deps/ex_cldr/lib/cldr/plural_rules/plural_rule.ex", :unknown_function},
  {"deps/ex_cldr_numbers/lib/cldr/number/backend/format.ex", :unknown_function},
  {"deps/ex_cldr_numbers/lib/cldr/number/backend/number.ex", :unknown_function},
  {"deps/ex_cldr_numbers/lib/cldr/number/backend/symbol.ex", :unknown_function},
  {"deps/ex_cldr_numbers/lib/cldr/number/backend/system.ex", :unknown_function},
  {"deps/ex_cldr_numbers/lib/cldr/number/backend/transliterate.ex", :unknown_function},
  {"deps/ex_cldr_numbers/lib/cldr/number/rbnf/processor.ex", :unknown_function},
  {"deps/ex_cldr_calendars/lib/cldr/calendar/backend/calendar.ex", :unknown_function},
  {"deps/ex_cldr_dates_times/lib/cldr/backend/format.ex", :unknown_function},
  {"deps/phoenix/lib/phoenix/endpoint.ex", :callback_info_missing},
  {"deps/phoenix/lib/phoenix/router.ex", :callback_info_missing},
  {"deps/plug/lib/plug/debugger.ex", :unknown_function},
  {"lib/cldr/unit.ex", :unknown_type},
  {"lib/klepsidra/ex_cldr.ex", :unknown_function},
  {"lib/klepsidra/ex_cldr.ex", :unknown_type},
  {"lib/klepsidra/mailer.ex", :unknown_function},
  {"lib/klepsidra/utilities/hash_functions.ex", :no_return},
  {"lib/klepsidra/utilities/hash_functions.ex", :extra_range},
  {"lib/klepsidra_web/klepsidra_csp.ex", :unknown_function},
  {"lib/klepsidra_web/components/layouts.ex", :unknown_function},
  {"lib/klepsidra_web/components/layouts/root.html.heex", :unknown_function},
  {"lib/klepsidra_web/controllers/page_html.ex", :unknown_function},
  {"lib/klepsidra_web/endpoint.ex", :unknown_function},
  {"lib/klepsidra_web/endpoint.ex", :unmatched_return},
  {"lib/klepsidra_web/router.ex", :unknown_function},
  {"lib/klepsidra_web/router.ex", :unmatched_return},
  {"lib/klepsidra_web/live/start_page_live.ex", :call},
  {"lib/klepsidra_web/live/start_page_live.ex", :no_return},
  {"lib/klepsidra_web/live/start_page_live.ex", :unused_fun}
  # {"lib/klepsidra_web/live/start_page_live.html.heex", :unknown_function}
]
