import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :klepsidra, KlepsidraWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  live_reload: [
    notify: [
      live_view: [
        ~r"lib/klepsidra_web/components/core_components.ex$",
        ~r"lib/klepsidra_web/(live|components)/.*(ex|heex)$"
      ]
    ],
    patterns: [
      ~r{priv/static/assets/generated_styles.css}
    ]
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Klepsidra.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
