defmodule Klepsidra.Repo.Migrations.CreateReports do
  use Ecto.Migration

  def change do
    create table(:reports,
             primary_key: false,
             comment:
               "Registered reports table, listing all available reports that can be generated by the system"
           ) do
      add :id, :uuid,
        primary_key: true,
        null: false,
        comment: "UUID-based relationship type primary key"

      add :report_name, :string,
        null: false,
        comment: "A report name, in human understandable language"

      add :system_report_name, :string,
        null: false,
        comment:
          "A report name, for machine consumption. It must not include spaces (underscore delimited words), 'illegal' non-ASCII characters, using only lowercase characters."

      add :report_template_name, :string,
        null: false,
        default: "Default",
        comment:
          "The system permits endless customisation of reports, and accepts the registration of multiple template designs and layouts, for the same report. This field specifies the name of this particular template or report variation"

      add :description, :text,
        comment: "Brief description of the report type and its intended use"

      add :template_path, :string,
        null: false,
        comment:
          "Absolute path of the report template file (`.jrxml`), which will be used to correctly typeset and lay out the report"

      add :output_types, :string,
        null: false,
        default: "pdf",
        comment:
          "Choice of the type of output file desired, from a selection of: PDF, HTML, Excel (XLS), Word (DOCX), PowerPoint (PPTX), OpenDocument Text (ODT), OpenDocumnet Spreadsheet (ODS)"

      add :output_filename_template, :string,
        null: false,
        default: "{system_report_name}_{date}.pdf",
        comment:
          "Template defining how the output report file will be named. Use of brackets `{` and `}` allows specification of common replacement patterns, which will be substituted at point of job request."

      timestamps()
    end

    create unique_index(:reports, [:report_name, :system_report_name, :report_template_name],
             comment:
               "Composite unique index of the report name and its template name, comprising the `report_name`, `system_report_name` and `report_template_name` fields"
           )

    create index(:reports, :report_name,
             comment:
               "Index of the `report_name` field, optimising searches filtering and ordering report names"
           )

    create index(:reports, :system_report_name,
             comment:
               "Index of the `system_report_name` field, optimising searches filtering and ordering machine-named reports by name"
           )

    create index(:reports, :report_template_name,
             comment:
               "Index of the `report_template_name` field, optimising searches filtering and ordering report template names"
           )

    create index(:reports, :output_types,
             comment:
               "Index of the `output_types` field, optimising searches filtering and ordering reports by their output type"
           )
  end
end
